# Generated by Django 5.1.7 on 2025-03-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelforBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'channel_for_receive',
            },
        ),
        migrations.CreateModel(
            name='Channelforforced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'forced_channel',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('ganre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('tili', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=40)),
                ('film', models.TextField(blank=True, null=True)),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'reklama',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('count_series', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('ganre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('tili', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=40)),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'serial',
            },
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('balans', models.IntegerField(default=0)),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_ban', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vipbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(max_length=15)),
                ('expiry_date', models.IntegerField()),
            ],
            options={
                'db_table': 'vip',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('wallet_id', models.BigIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.IntegerField()),
                ('part', models.TextField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serial')),
            ],
            options={
                'db_table': 'series',
            },
        ),
    ]
